"""The event vocabulary.

Named here rather than as string literals scattered across five parts, so the
security dashboard can offer a filter list that matches what is actually
written, and so a typo in an event type is a missing constant rather than a
silently unfilterable row.
"""

from __future__ import annotations

# Lifecycle
TASK_STARTED = "TASK_STARTED"
TASK_COMPLETED = "TASK_COMPLETED"
TASK_FAILED = "TASK_FAILED"
TASK_CANCELLED = "TASK_CANCELLED"

# Decisions
MODEL_SELECTED = "MODEL_SELECTED"
TOOL_CALLED = "TOOL_CALLED"
TOOL_DENIED = "TOOL_DENIED"
SANDBOX_STARTED = "SANDBOX_STARTED"

# Data
DOCUMENT_INGESTED = "DOCUMENT_INGESTED"
DOCUMENT_ACCESSED = "DOCUMENT_ACCESSED"
KNOWLEDGE_RETRIEVED = "KNOWLEDGE_RETRIEVED"
ARTIFACT_GENERATED = "ARTIFACT_GENERATED"
ARTIFACT_DOWNLOADED = "ARTIFACT_DOWNLOADED"

# Identity and platform actions. These are emitted by Part 01 and were
# missing from the tuple below, which is what the dashboard offers as its
# filter list -- an event type that is written but not listed is one nobody
# can filter for.
LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED"
LOGIN_FAILED = "LOGIN_FAILED"
LOGIN_THROTTLED = "LOGIN_THROTTLED"
LOGOUT = "LOGOUT"
CONVERSATION_CREATED = "CONVERSATION_CREATED"
FILE_UPLOADED = "FILE_UPLOADED"
FILE_DELETED = "FILE_DELETED"
UPLOAD_REJECTED = "UPLOAD_REJECTED"
INGESTION_FAILED = "INGESTION_FAILED"
MODEL_REGISTRY_REFRESHED = "MODEL_REGISTRY_REFRESHED"

# People
APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
APPROVAL_GRANTED = "APPROVAL_GRANTED"
APPROVAL_DENIED = "APPROVAL_DENIED"
PERMISSION_DENIED = "PERMISSION_DENIED"

# Sovereignty
EXTERNAL_CALL_ATTEMPTED = "EXTERNAL_CALL_ATTEMPTED"

EVENT_TYPES = (
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGIN_THROTTLED,
    LOGOUT,
    CONVERSATION_CREATED,
    FILE_UPLOADED,
    FILE_DELETED,
    UPLOAD_REJECTED,
    INGESTION_FAILED,
    MODEL_REGISTRY_REFRESHED,
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_CANCELLED,
    MODEL_SELECTED,
    TOOL_CALLED,
    TOOL_DENIED,
    SANDBOX_STARTED,
    DOCUMENT_INGESTED,
    DOCUMENT_ACCESSED,
    KNOWLEDGE_RETRIEVED,
    ARTIFACT_GENERATED,
    ARTIFACT_DOWNLOADED,
    APPROVAL_REQUESTED,
    APPROVAL_GRANTED,
    APPROVAL_DENIED,
    PERMISSION_DENIED,
    EXTERNAL_CALL_ATTEMPTED,
)
